//! CRI v1 gRPC client for the rusternetes kubelet.
//!
//! This crate is the kubelet's southbound runtime backend: it speaks the
//! Kubernetes Container Runtime Interface (`runtime.v1`, gRPC) to a
//! CRI-conformant runtime such as containerd (which in turn drives an OCI
//! runtime like Youki). It replaces the Docker-API (bollard) coupling that tied
//! the kubelet to Podman/Docker.
//!
//! The generated gRPC types live under [`v1`]. Consumers should prefer the
//! domain-typed [`CriClient`] wrapper so the raw tonic surface stays isolated
//! and the backend can later be pointed at a Rust CRI server without touching
//! the kubelet.

use std::path::{Path, PathBuf};

use hyper_util::rt::TokioIo;
use tonic::transport::{Channel, Endpoint, Uri};
use tower::service_fn;

/// Generated CRI v1 protobuf/gRPC types (`package runtime.v1`).
///
/// The contents are machine-generated by tonic-build from the vendored proto;
/// lints are silenced because we do not own its style (doc formatting, large
/// enum variants, etc.).
#[allow(clippy::all, clippy::pedantic, clippy::nursery, rustdoc::all)]
pub mod v1 {
    tonic::include_proto!("runtime.v1");
}

use v1::image_service_client::ImageServiceClient;
use v1::runtime_service_client::RuntimeServiceClient;

/// Errors surfaced by the CRI client.
#[derive(Debug, thiserror::Error)]
pub enum CriError {
    /// Failed to establish the gRPC channel to the runtime socket.
    #[error("failed to connect to CRI socket {socket}: {source}")]
    Connect {
        socket: String,
        #[source]
        source: tonic::transport::Error,
    },

    /// A gRPC call returned an error status.
    #[error("CRI rpc {rpc} failed: {source}")]
    Rpc {
        rpc: &'static str,
        #[source]
        source: tonic::Status,
    },

    /// The socket path was not a valid endpoint.
    #[error("invalid CRI endpoint: {0}")]
    Endpoint(#[source] tonic::transport::Error),
}

/// Result alias for CRI operations.
pub type Result<T> = std::result::Result<T, CriError>;

/// A connected CRI v1 client.
///
/// Holds both the `RuntimeService` and `ImageService` clients over a single
/// shared [`Channel`] (cloning a tonic `Channel` shares the underlying
/// connection pool, so the two services do not open separate sockets).
#[derive(Clone)]
pub struct CriClient {
    runtime: RuntimeServiceClient<Channel>,
    image: ImageServiceClient<Channel>,
    socket: PathBuf,
}

impl CriClient {
    /// Connect to a CRI runtime listening on a Unix domain socket.
    ///
    /// `socket` is a filesystem path (e.g. `/run/containerd/containerd.sock`).
    /// The `unix://` URI scheme is accepted and stripped. tonic 0.12 rides
    /// hyper 1.x, so the tokio `UnixStream` is wrapped in [`TokioIo`] before the
    /// transport will accept it; the HTTP authority in the dummy URI is ignored
    /// because the custom connector dials the socket directly.
    pub async fn connect(socket: impl AsRef<Path>) -> Result<Self> {
        let socket = normalize_socket_path(socket.as_ref());
        let socket_for_conn = socket.clone();

        // The URI is a placeholder required by Endpoint; the connector below
        // ignores its authority and always dials the fixed socket path.
        let endpoint = Endpoint::try_from("http://[::]:50051").map_err(CriError::Endpoint)?;

        let channel = endpoint
            .connect_with_connector(service_fn(move |_: Uri| {
                let path = socket_for_conn.clone();
                async move {
                    let stream = tokio::net::UnixStream::connect(path).await?;
                    Ok::<_, std::io::Error>(TokioIo::new(stream))
                }
            }))
            .await
            .map_err(|source| CriError::Connect {
                socket: socket.display().to_string(),
                source,
            })?;

        Ok(Self {
            runtime: RuntimeServiceClient::new(channel.clone()),
            image: ImageServiceClient::new(channel),
            socket,
        })
    }

    /// The socket path this client is connected to.
    pub fn socket(&self) -> &Path {
        &self.socket
    }

    /// Mutable access to the raw `RuntimeService` client.
    ///
    /// Later sub-projects (sandbox/container lifecycle, status, exec) build
    /// domain-typed methods on top of this; for now it is the escape hatch.
    pub fn runtime(&mut self) -> &mut RuntimeServiceClient<Channel> {
        &mut self.runtime
    }

    /// Mutable access to the raw `ImageService` client.
    pub fn image(&mut self) -> &mut ImageServiceClient<Channel> {
        &mut self.image
    }

    /// Perform the CRI `Version` handshake.
    ///
    /// The kubelet calls this at startup to confirm the runtime speaks CRI v1.
    /// `api_version` in the request is advisory; the response carries the
    /// runtime's name/version and the CRI API version it implements.
    pub async fn version(&mut self) -> Result<v1::VersionResponse> {
        let request = v1::VersionRequest {
            version: "v1".to_string(),
        };
        let response = self
            .runtime
            .version(request)
            .await
            .map_err(|source| CriError::Rpc {
                rpc: "Version",
                source,
            })?;
        Ok(response.into_inner())
    }
}

/// Strip a `unix://` (or `unix:`) scheme from a socket path, leaving a bare
/// filesystem path for `UnixStream::connect`.
fn normalize_socket_path(socket: &Path) -> PathBuf {
    let s = socket.to_string_lossy();
    let trimmed = s
        .strip_prefix("unix://")
        .or_else(|| s.strip_prefix("unix:"))
        .unwrap_or(&s);
    PathBuf::from(trimmed)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn strips_unix_scheme() {
        assert_eq!(
            normalize_socket_path(Path::new("unix:///run/containerd/containerd.sock")),
            PathBuf::from("/run/containerd/containerd.sock")
        );
        assert_eq!(
            normalize_socket_path(Path::new("unix:/run/foo.sock")),
            PathBuf::from("/run/foo.sock")
        );
        assert_eq!(
            normalize_socket_path(Path::new("/run/bare.sock")),
            PathBuf::from("/run/bare.sock")
        );
    }

    /// The generated client types exist and the version request is constructible.
    /// Pure compile/smoke check — no socket required.
    #[test]
    fn generated_types_present() {
        let req = v1::VersionRequest {
            version: "v1".to_string(),
        };
        assert_eq!(req.version, "v1");
    }

    /// Socket-gated live handshake. Skips unless RUSTERNETES_CRI_SOCKET points at
    /// a real CRI runtime — keeps `cargo test` green on machines without one.
    #[tokio::test]
    async fn version_handshake_against_real_runtime() {
        let Ok(socket) = std::env::var("RUSTERNETES_CRI_SOCKET") else {
            eprintln!("RUSTERNETES_CRI_SOCKET unset; skipping live CRI handshake");
            return;
        };
        let mut client = CriClient::connect(&socket)
            .await
            .expect("connect to CRI socket");
        let v = client.version().await.expect("CRI Version handshake");
        eprintln!(
            "CRI runtime: {} {} (api {})",
            v.runtime_name, v.runtime_version, v.version
        );
        assert!(!v.version.is_empty());
    }
}
